In [3]:
import pandas as pd
import numpy as np 


In [4]:
df=pd.read_csv("dimDate.csv")

In [6]:
df.describe()

dimDatePostPK         Year    MonthPeriod         Day
count   2.240000e+02   224.000000     224.000000  224.000000
mean    2.019971e+07  2019.924107  201996.946429   16.026786
std     2.445149e+03     0.265420      24.471577    8.667717
min     2.019122e+07  2019.000000  201912.000000    1.000000
25%     2.020021e+07  2020.000000  202002.000000    9.000000
50%     2.020040e+07  2020.000000  202004.000000   16.000000
75%     2.020053e+07  2020.000000  202005.000000   23.000000
max     2.020073e+07  2020.000000  202007.000000   31.000000

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]
